mysite/blog/urls.py
from django.contrib.auth.urls import url
from . import views

urlpatterns = [
    url(r'^home/$', views.home, name='home'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name = 'post_share'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post_detail'),
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('blog.urls', namespace='blog', app_name='blog'))
]

mysite/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.urlresolvers import reverse
# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset()\
                                            .filter(status='published')

class Post(models.Model):
    CHOISE = (('draft', 'Draft'), ('published', 'Published'),)

    title = models.CharField(max_length=250)
    author = models.ForeignKey(User, related_name='blog_posts')
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, default='draft', choices=CHOISE)

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ['-publish']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[
            self.publish.year,
            self.publish.strftime('%m'),
            self.publish.strftime('%d'),
            self.slug
        ])


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment By {} on {}'.format(self.name, self.post)
class Contact(models.Model):
    name = models.CharField(max_length=120, blank=False)
    email = models.EmailField(blank=True)
    subject = models.CharField(max_length=200, blank=False)
    message = models.TextField()
    sent = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-sent']

    def __str__(self):
        return self.subject

mysite/blog/forms.py
from django import forms
from .models import Comment, Contact

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'email', 'subject', 'message')

mysite/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, ContactForm
from django.core.mail import send_mail

# Create your views here.

def home(request):
    posts = Post.objects.filter(status='published')
    return render(request, 'blog/blogs.html', {'posts': posts})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                            status='published',
                            slug=post,
                            publish__year=year,
                            publish__month=month,
                            publish__day=day)
    comments = post.comments.filter(active=True)

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, 'blog/post/detail.html', {'post': post, 'comment_form': comment_form, 'comments': comments})

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == "POST":
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())

            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'fordjangouse@gmail.com', [cd['to']])
            sent =True
    else:
        form = EmailPostForm()

    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})

def contact(request):
    if request.POST:
        form_contact = ContactForm(data=request.POST)
        if form_contact.is_valid():
            form_contact.save()
    else:
        form_contact = ContactForm()

    return render(request, 'blog/post/contact.html', {'form_contact': form_contact})

mysite/blog/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>The Blogger</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">

  </head>

  <body>

    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">

          <a class="navbar-brand" href="/home/">The Blogger</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/home">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="/contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


       {% block blogs %}

       {% endblock %}

        <!-- /.container -->




    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/docs.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>


mysite/blog/templates/blog/blogs.html
{% extends 'base.html' %}
{% block blogs %}
   <div class="col-sm-8 blog-main">
       <div class="container">

      <div class="blog-header">
        <h1 class="blog-title">The Blogger</h1>
      </div>

      <div class="row">
        {% for post in posts %}
          <div class="blog-post">
            <h2 class="blog-post-title"><a href="{{ post.get_absolute_url }}"> {{ post.title }}</a></h2>
            <p class="blog-post-meta">Published {{ post.publish }} By <a href="#">{{ post.author }}</a></p>
            <hr>
            <p>{{ post.body|truncatewords:30|linebreaks }}</p>
            <hr>

          </div>
        {% endfor %}
          <nav>
            <ul class="pager">
              <li><a href="#">Previous</a></li>
              <li><a href="#">Next</a></li>
            </ul>
          </nav>

          <!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div>

          </div>
{% endblock %}

mysite/blog/templates/blog/post/contact.html
{% extends 'base.html' %}
{% block blogs %}
        <h1>Contact Us!</h1>
        <form action="." method="post">
            {{ form_contact.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send">
        </form>
{% endblock %}

mysite/blog/templates/blog/post/detail.html
{% extends 'base.html' %}

{% block blogs %}
      <div class="col-sm-8 blog-main">
       <div class="container">

      <div class="blog-header">
        <h1 class="blog-title">{{ post.title }}</h1>
      </div>

      <div class="row">
          <div class="blog-post">
            <p class="blog-post-meta">Published {{ post.publish }} By <a href="#">{{ post.author }}</a></p>
            <hr>
            <p>{{ post.body|linebreaks }}</p>
            <p>
                <a href="{% url 'blog:post_share' post.id %}">
                    Share this post
                </a>
            </p>
              <br>
              <br>
              {% with comments.count as total_comments %}
                 <h2>
                     {{ total_comments }} comment{{ total_comments|pluralize}}
                 </h2>
              {% endwith %}
              {% for comment in comments %}
                 <div>
                     <br>
                     <p>
                         Comment {{ forloop.counter }} by {{ comment.name }}
                         {{ comment.created }}
                     </p>

                     <h2>{{ comment.name }}</h2>
                     {{ comment.body|linebreaks }}
                 </div>
              {% empty %}
                   <p>There are no comments. Be the first to comment</p>
              {% endfor %}
              {% if new_comment %}
                <h2>Your comment has been added</h2>
              {% else %}
                <br>
                <h2>Add a new comment</h2>
                <form action="." method="post">
                    {{ comment_form.as_p }}
                    {% csrf_token %}
                    <p><input type="submit" value="Add comment"></p>
                </form>
              {% endif %}
            <hr>

          </div>
          <!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div>

          </div>
{% endblock %}

mysite/blog/templates/blog/post/share.html
{% extends "base.html" %}

{% block blogs %}
    {% if sent %}
       <h1>Email successfully sent</h1>
       <p>
           "{{ post.title }}" was successfully sent to {{ cd.to }}
       </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}

{% endblock %}